### ISSUE TITLE
Error when migrating snapshot with multiple partitions

### ISSUE THREAD

**Issue by mrushdan** [thenickdude/snap-to-s3#12] opened 2019-10-26 02:56 UTC
```
Uploading partition 2 of 2...
[snap-068329d799735982a] Mounting /dev/nvme3n1p128 at /mnt/snap-068329d799735982a-p128...
[snap-068329d799735982a] An error occurred, tagging snapshot with "migrate" so it can be retried later
[snap-068329d799735982a] { Error: snap-068329d799735982a: mount --source /dev/nvme3n1p128 --target /mnt/snap-068329d799735982a-p128 --read-only failed:  mount: /mnt/snap-068329d799735982a-p128: wrong fs type, bad option, bad superblock on /dev/nvme3n1p128, missing codepage or helper program, or other error.
    at _raceToMarkSnapshot.then.then (/home/ec2-user/snap-to-s3-master/lib/snap-to-s3.js:1691:12)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  error: 'mount --source /dev/nvme3n1p128 --target /mnt/snap-068329d799735982a-p128 --read-only failed:  mount: /mnt/snap-068329d799735982a-p128: wrong fs type, bad option, bad superblock on /dev/nvme3n1p128, missing codepage or helper program, or other error.\n',
  snapshotID: 'snap-068329d799735982a' }

Terminating due to fatal errors.
```

**Comment by thenickdude** [comment] 2019-10-26 02:59
Duplicate of #10

**Closed as completed by thenickdude** 2019-10-26 02:59 UTC
